USE MuseumDB
GO

DELETE FROM IsVisited;
DELETE FROM Visit;

DELETE FROM Visitor;

DELETE FROM Exhibition;
DELETE FROM Exhibit;

DELETE FROM Date;
--DELETE FROM Time;
DELETE FROM Room;

DBCC CHECKIDENT ('Room', RESEED, 0);
DBCC CHECKIDENT ('Visitor', RESEED, 0);
DBCC CHECKIDENT ('Exhibition', RESEED, 0);
DBCC CHECKIDENT ('Exhibit', RESEED, 0);
DBCC CHECKIDENT ('Date', RESEED, 0);
--DBCC CHECKIDENT ('Time', RESEED, 0);
DBCC CHECKIDENT ('Visit', RESEED, 0);